/************************************************************************
 * NASA Docket No. GSC-18,719-1, and identified as “core Flight System: Bootes”
 *
 * Copyright (c) 2020 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************/

/* PSP coverage stub replacement for memPartLib.h */
#include <string.h>
#include <stdlib.h>
#include "utstubs.h"

#include "PCS_gr740.h"

static uint32_t PCS_APBUART0_REG_ADDR_VALUE;
static uint32_t PCS_GRGPIO0_REG_ADDR_VALUE;
static uint32_t PCS_FTMCTRL_REG_ADDR_VALUE;
static uint32_t PCS_IRQAMP_REG_ADDR_VALUE;
static SPARC_LEON4_TIMER_REG_T PCS_GPTIMER0_REG_ADDR_VALUE;
static SPARC_LEON4_TIMER_REG_T PCS_GPTIMER1_REG_ADDR_VALUE;
static SPARC_LEON4_TIMER_REG_T PCS_GPTIMER2_REG_ADDR_VALUE;
static SPARC_LEON4_TIMER_REG_T PCS_GPTIMER3_REG_ADDR_VALUE;
static SPARC_LEON4_TIMER_REG_T PCS_GPTIMER4_REG_ADDR_VALUE;
static uint32_t PCS_GRSPWROUTER0_REG_ADDR_VALUE;
static uint32_t PCS_GRSPWROUTER1_REG_ADDR_VALUE;
static uint32_t PCS_GRSPWROUTER2_REG_ADDR_VALUE;
static uint32_t PCS_GRSPWROUTER3_REG_ADDR_VALUE;
static uint32_t PCS_GRETH_GBIT0_REG_ADDR_VALUE;
static uint32_t PCS_GRETH_GBIT1_REG_ADDR_VALUE;
static uint32_t PCS_APBBRIDGE0_REG_ADDR_VALUE;
static uint32_t PCS_APBBRIDGE1_REG_ADDR_VALUE;
static SPARC_LEON4_MEMORY_SCRUBBER_REG_T PCS_MEMSCRUB_REG_ADDR_VALUE;
static TEMPERATURE_REG_T PCS_GR740THSEND_REG_ADDR_VALUE;
static GPRB_REG_T PCS_GRGPRBANK_REG_ADDR_VALUE;
static L4STAT_REG_T PCS_L4STAT_REG_ADDR_VALUE;

uint32_t *PCS_APBUART0_REG_ADDR = &PCS_APBUART0_REG_ADDR_VALUE;
uint32_t *PCS_GRGPIO0_REG_ADDR = &PCS_GRGPIO0_REG_ADDR_VALUE;
uint32_t *PCS_FTMCTRL_REG_ADDR = &PCS_FTMCTRL_REG_ADDR_VALUE;
uint32_t *PCS_IRQAMP_REG_ADDR = &PCS_IRQAMP_REG_ADDR_VALUE;
SPARC_LEON4_TIMER_REG_T *PCS_GPTIMER0_REG_ADDR = &PCS_GPTIMER0_REG_ADDR_VALUE;
SPARC_LEON4_TIMER_REG_T *PCS_GPTIMER1_REG_ADDR = &PCS_GPTIMER1_REG_ADDR_VALUE;
SPARC_LEON4_TIMER_REG_T *PCS_GPTIMER2_REG_ADDR = &PCS_GPTIMER2_REG_ADDR_VALUE;
SPARC_LEON4_TIMER_REG_T *PCS_GPTIMER3_REG_ADDR = &PCS_GPTIMER3_REG_ADDR_VALUE;
SPARC_LEON4_TIMER_REG_T *PCS_GPTIMER4_REG_ADDR = &PCS_GPTIMER4_REG_ADDR_VALUE;
uint32_t *PCS_GRSPWROUTER0_REG_ADDR = &PCS_GRSPWROUTER0_REG_ADDR_VALUE;
uint32_t *PCS_GRSPWROUTER1_REG_ADDR = &PCS_GRSPWROUTER1_REG_ADDR_VALUE;
uint32_t *PCS_GRSPWROUTER2_REG_ADDR = &PCS_GRSPWROUTER2_REG_ADDR_VALUE;
uint32_t *PCS_GRSPWROUTER3_REG_ADDR = &PCS_GRSPWROUTER3_REG_ADDR_VALUE;
uint32_t *PCS_GRETH_GBIT0_REG_ADDR = &PCS_GRETH_GBIT0_REG_ADDR_VALUE;
uint32_t *PCS_GRETH_GBIT1_REG_ADDR = &PCS_GRETH_GBIT1_REG_ADDR_VALUE;
uint32_t *PCS_APBBRIDGE0_REG_ADDR = &PCS_APBBRIDGE0_REG_ADDR_VALUE;
uint32_t *PCS_APBBRIDGE1_REG_ADDR = &PCS_APBBRIDGE1_REG_ADDR_VALUE;
SPARC_LEON4_MEMORY_SCRUBBER_REG_T *PCS_MEMSCRUB_REG_ADDR = &PCS_MEMSCRUB_REG_ADDR_VALUE;
TEMPERATURE_REG_T *PCS_GR740THSEND_REG_ADDR = &PCS_GR740THSEND_REG_ADDR_VALUE;
GPRB_REG_T *PCS_GRGPRBANK_REG_ADDR = &PCS_GRGPRBANK_REG_ADDR_VALUE;
L4STAT_REG_T *PCS_L4STAT_REG_ADDR  = &PCS_L4STAT_REG_ADDR_VALUE;
